# Generated by Django 4.2 on 2024-05-27 21:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("UserProfile", "0002_alter_profile_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="phone_number",
        ),
    ]
