# Generated by Django 4.2 on 2024-05-27 23:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("UserProfile", "0005_profile_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
    ]
